# Assignment 1: Introduction to the Fully Recurrent Network

*Author:* Thomas Adler

*Copyright statement:* This  material,  no  matter  whether  in  printed  or  electronic  form,  may  be  used  for  personal  and non-commercial educational use only.  Any reproduction of this manuscript, no matter whether as a whole or in parts, no matter whether in printed or in electronic form, requires explicit prior acceptance of the authors.


## Exercise 1: Numerical stability of the binary cross-entropy loss function

We will use the binary cross-entropy loss function to train our RNN, which is defined as 
$$
L_{\text{BCE}}(\hat y, y) = -y \log \hat y - (1-y) \log (1-\hat y),
$$
where $y$ is the label and $\hat y$ is a prediction, which comes from a model (e.g. an RNN) and is usually sigmoid-activated, i.e., we have
$$
\hat y = \sigma(z) = \frac{1}{1+e^{-z}}.
$$
The argument $z$ is called *logit*. For reasons of numerical stability it is better to let the model emit the logit $z$ (instead of the prediction $\hat y$) and incorporate the sigmoid activation into the loss function. Explain why this is the case and how we can gain numerical stability by combining the two functions $L_{\text{BCE}}(\hat y, y)$ and $\sigma(z)$ into one function $L(z, y) = L_{\text{BCE}}(\sigma(z), y)$. 

*Hint: Prove that $\log(1+e^{z}) = \log (1+e^{-|z|}) + \max(0, z)$ and argue why the right-hand side is numerically more stable. Finally, express $L(z,y)$ in terms of that form.*

########## YOUR SOLUTION HERE ##########


In order to show that the numerical stability of $\newline$

$L_{\text{BCE}}(\hat y, y) = -y \log \hat y - (1-y) \log (1-\hat y)$ $\newline$

is better if we let the model emit the logit $z$ and incorporate the sigmoid activation into the loss function, we have to understand numerical stability.

Start with substituting $\hat y$ through $\sigma(z)$:

$L_{\text{BCE}}(\sigma(z), y) = -y \log(\frac{1}{1+e^{-z}}) - (1 - y) \log(1 - \frac{1}{1+e^{-z}})$

In this occasion, the equation is numerically unstable because of the logarithms. These logarithms can become unstable if $\hat y$ is getting close to 0 or 1. These values could be within reach if $z$ of $\newline$

$\sigma(z) = \frac{1}{1+e^{-z}}$

is either very large or very negative. $\newline$
If $z$ is really negative, the $\hat y$ will become close to 0, which leads to $\log(\hat y)$ becomming very large negative which can lead to an underflow. $\newline$

If $z$ is really large, the $\hat y$ will become close to 1, which leads to $\log(1 -\hat y)$ becomming very large negative which can lead to precision errors. $\newline$

Instead of first calculating $\hat y = \sigma(z)$ and then applying the BCE loss, we can merge the sigmoid function and BCE loss into a single step to make numerical stability better. This involves expressing the loss function directly in terms of the logits $z$.


$L_(z,y) = L_{\text{BCE}}(\sigma(z), y) = -y \log(\sigma(z)) - (1 - y) \log(1 - \sigma(z))$ $\newline$

Now take a different form (identity) of the logs to express $z$ directly: $\newline$

$\log(\sigma(z)) = -\log({1+e^{-z}})$

$\log(1 - \sigma(z)) = -\log({1+e^{z}})$  $\newline$

Now put this back in the equation:$\newline$

$L(z,y) = y \log(1 + e^{-z}) + (1 - y) \log(1 + e^{z})$ $\newline$

Now make use of the relation: $\newline$

$\log(1+e^{−z}) = \log(e^{−z} (e^{z}+1)) = \log(e^{−z}) + \log(1+e^{z})=−z+log(1+e^{z})$ $\newline$

And if you plug that in, in the end you get the solution:$\newline$

$L(z,y) = \log(1 + e^{z}) - yz$ $\newline$

Now we can see that this works for very small $z$, but not for big ones. Therefore we have to look back at the hint: $\newline$

$\log(1+e^{z}) = \log (1+e^{-|z|}) + \max(0, z)$ $\newline$

If we take that identity, we get $\newline$

$L(z,y) = \log(1+e^{-(-z)}) + max(0,z) - yz$ $\newline$

which works for both big an small $z$. $\newline$


## Exercise 2: Derivative of the loss

Calculate the derivative of the binary cross-entropy loss function $L(z, y)$ with respect to the logit $z$.

########## YOUR SOLUTION HERE ##########

As mentioned above, the next exercise revolves around derivative of $L(z,y)$. $\newline$
First of all, we take the function $\newline$

$L(z,y) = \log(1+e^{-(-z)}) + max(0,z) - yz$ $\newline$

and rewrite it back to standard formulation because in this form, the derivative is harder to compute due to our numerical stability modifications. We also substitute $\newline$

$\hat y = \sigma(z)$    $\newline$

so we get:  $\newline$

$L(z,y) = -y \log(\sigma(z)) - (1 - y) \log(1 - \sigma(z))$ $\newline$

To further continue, we start by differntiating the sigmoid function with respect to $z$ instead of the total loss function: $\newline$

$\frac{d}{dz} \sigma(z) = \sigma(z)(1-\sigma(z))$ $\newline$

Afterwards, we start differentiating $L(z,y)$:

$\frac{dL}{dz} = \frac{d}{dz} (-y \log(\sigma(z)) - (1- y)\log(1 - \sigma(z)))$ $\newline$

First we apply the chain rule and calculate the derivative for first term, so for $\newline$

$-y\log(\sigma(z))$ $\newline$

we get (log for fracture): $\newline$

$\frac{d}{dz}(-y\log(\sigma(z))) = -y * \frac{1}{\sigma(z)} *  \frac{d}{dz} \sigma(z)  = -y * \frac{1}{\sigma(z)} * \sigma(z) (1 - \sigma(z)) = -y (1 - \sigma(z))$ $\newline$

Now we take a look at the second term being $\newline$

$-(1 - y) \log(1 - \sigma(z))$ $\newline$

so we get: $\newline$

$\frac{d}{dz} (-(1 - y) \log(1 - \sigma(z))) = -(1 - y) * \frac{1}{1 - \sigma(z)} * \frac{d}{dz} (-\sigma(z)) = (1 - y) * \frac{1}{1 - \sigma(z)} * \sigma(z) (1- \sigma(z)) = (1 - y) \sigma(z)$ $\newline$

Now that both terms have been differentiated, we have to combine them: $\newline$

$\frac{dL}{dz} = -y(1 - \sigma(z)) + (1 - y)\sigma(z)$ $\newline$

which can be shortened to: $\newline$

$\frac{dL}{dz} = \sigma(z) - y$

## Exercise 3: Initializing the network
Consider the fully recurrent network
$$
s(t) = W x(t) + R a(t-1) \\
a(t) = \tanh(s(t)) \\
z(t) = V a(t) \\
\hat y(t) = \sigma(z(t))
$$
for $t \in \mathbb{N}, x(t) \in \mathbb{R}^{D}, s(t) \in \mathbb{R}^{I}, a(t) \in \mathbb{R}^{I}, z(t) \in \mathbb{R}^K, \hat y(t) \in \mathbb{R}^K$ and $W, R, V$ are real matrices of appropriate sizes and $\hat a(0) = 0$. 

*Compared to the lecture notes we choose $f(x) = \tanh(x) = (e^x - e^{-x})(e^x + e^{-x})^{-1}$ and $\varphi(x) = \sigma(x) = (1+e^{-x})^{-1}$. Further, we introduced an auxiliary variable $z(t)$ and transposed the weight matrices.*

Write a function `init` that takes a `model` and integers $D, I, K$ as arguments and stores the matrices $W, R, V$ as members `model.W`, `model.R`, `model.V`, respectively. The matrices should be `numpy` arrays of appropriate sizes and filled with random values that are uniformly distributed between -0.01 and 0.01. 

In [21]:
%matplotlib inline

import numpy as np
from scipy.special import expit as sigmoid

class Obj(object):
    pass

model = Obj()
T, D, I, K = 10, 3, 5, 1

def init(model, D, I, K):
    ########## YOUR SOLUTION HERE ##########

    # T = number of timesteps, D = input vector, I = hidden layer units, K = output vector
    model.W = np.random.uniform(-0.01, 0.01, (I, D))
    model.R = np.random.uniform(-0.01, 0.01, (I, I))
    model.V = np.random.uniform(-0.01, 0.01, (K, I))

Obj.init = init
model.init(D, I, K)

# Check the initialized values
print("W:\n", model.W)
print("W shape:\n", model.W.shape)
print("R:\n", model.R)
print("R shape:\n", model.R.shape)
print("V:\n", model.V)
print("V shape:\n", model.V.shape)


W:
 [[-0.00984992 -0.00330833  0.00642003]
 [ 0.00810275 -0.008969   -0.00852434]
 [-0.00146261  0.00662945  0.00417605]
 [-0.00500566 -0.00906989 -0.00773167]
 [ 0.00658207  0.00469923  0.00960752]]
W shape:
 (5, 3)
R:
 [[ 0.00031733 -0.00212176 -0.00962914 -0.00481064  0.0096519 ]
 [-0.0057268  -0.00467242 -0.00778849 -0.00013911 -0.00867697]
 [-0.00057974  0.00275389 -0.00753895 -0.0037674   0.00018284]
 [ 0.00706583 -0.00031165  0.00959283 -0.00878603  0.00337931]
 [-0.00273801  0.00773652  0.00502024 -0.00270665  0.00853739]]
R shape:
 (5, 5)
V:
 [[-0.00708561 -0.00208262  0.00812209  0.00193818  0.00794367]]
V shape:
 (1, 5)


## Exercise 4: The forward pass
Implement the forward pass for the fully recurrent network for sequence classification (many-to-one mapping). To this end, write a function `forward` that takes a `model`, a sequence of input vectors `x`, and a label `y` as arguments. The inputs will be represented as a `numpy` array of shape `(T, D)`. It should execute the behavior of the fully recurrent network and evaluate the (numerically stabilized) binary cross-entropy loss at the end of the sequence and return the resulting loss value. Store the sequence of hidden activations $(a(t))_{t=1}^T$ and the logit $z(T)$ into `model.a` and `model.z`, respectively. 

In [25]:
def forward(model, x, y):
    ########## YOUR SOLUTION HERE ##########

    T, D = x.shape  # T: number of time steps, D: input dimensionality
    I = model.W.shape[0]  # I: number of hidden units
    K = model.V.shape[0]  # K: number of output units (should be 1 for binary classification)

    # Initialize hidden activations and output
    a = np.zeros((T, I))  # store hidden activations for each time step
    z = np.zeros(K)       # store the output logit at time step T

    # Initialize the hidden state a(0) = 0
    a_t_minus_1 = np.zeros(I)

    # Forward pass through the sequence
    for t in range(T):
        s_t = np.dot(model.W, x[t]) + np.dot(model.R, a_t_minus_1)  # Compute s(t)
        a_t = np.tanh(s_t)  # Compute a(t)
        a[t] = a_t  # Store the hidden activation

        a_t_minus_1 = a_t  # Update a(t-1) for the next time step

    # Compute the final logit z(T) and output probability \hat y(T)
    z = np.dot(model.V, a[-1])  # z(T)
    y_hat = sigmoid(z)  # \hat y(T) = σ(z(T))

    # Compute the numerically stable binary cross entropy loss from the exercise before
    # L(z, y) = log(1 + exp(-(-z))) + max(0, z) - y * z
    loss = np.log(1 + np.exp(-(-z))) + np.maximum(0, z) - y * z

    # Store the sequence of hidden activations and final logit
    model.a = a
    model.z = z

    return loss

# Assign the forward function to the class
Obj.forward = forward

# Example to showcase the function
T, D, I, K = 10, 3, 5, 1  # Time steps, input size, hidden units, output size
model = Obj()  # Create an instance of Obj
model.W = np.random.uniform(-0.01, 0.01, (I, D))
model.R = np.random.uniform(-0.01, 0.01, (I, I))
model.V = np.random.uniform(-0.01, 0.01, (K, I))

# Forward pass with a random input sequence and label 1
x = np.random.uniform(-1, 1, (T, D))  # Random input sequence
y = 1  # Label

loss = model.forward(x, y)  # Compute the forward pass for the loss

# Print the final loss, hidden activations and the fnial logit
print(f"Final loss: {loss}")
print(f"Final hidden activations (a):\n{model.a}")
print(f"Final logit (z): {model.z}")

Final loss: [0.69314909]
Final hidden activations (a):
[[ 4.18406571e-03  4.16735306e-04  7.40404166e-04 -4.07381880e-03
  -1.35159127e-03]
 [-6.04714831e-03 -2.38519780e-03 -7.24768700e-03 -3.16236390e-04
  -1.25951315e-02]
 [-4.57321695e-03 -1.28436409e-03 -2.35731396e-03  2.46455443e-03
  -2.04097670e-03]
 [-5.73104388e-03 -6.65131570e-04 -1.15850226e-03  5.33414918e-03
   1.62807402e-03]
 [-1.56009912e-03  9.06235404e-04  9.55313928e-04  3.22811641e-03
   3.95929696e-03]
 [-7.47264252e-03 -2.92174073e-03 -8.30839008e-03  5.93390665e-05
  -1.40920884e-02]
 [ 6.60709211e-04 -3.38149793e-04 -2.65944384e-03 -3.30927865e-03
  -6.04181469e-03]
 [ 7.79800216e-03  6.92185369e-04  3.57884216e-03 -5.92786140e-03
   2.24429289e-03]
 [ 1.37561024e-03 -4.74424505e-04 -2.28564720e-03 -3.67986046e-03
  -6.50808192e-03]
 [-2.75229400e-03 -1.17872072e-04  1.06580667e-03  4.02149169e-03
   4.41146905e-03]]
Final logit (z): [-3.8100031e-06]


## Exercise 5: The computational graph

Visualize the computational graph of the fully recurrent network unfolded in time. The graph should show the functional dependencies of the nodes $x(t), a(t), z(t), L(z(t), y(t))$ for $t \in \{1, 2, 3\}$. Use the package `networkx` in combination with `matplotlib` to draw a directed graph with labelled nodes and edges. If you need help take a look at [this guide](https://networkx.org/documentation/stable/tutorial.html). Make sure to arrange the nodes in a meaningful way. 

In [ ]:
import networkx as nx
import matplotlib.pyplot as plt

########## YOUR SOLUTION HERE ##########

# Einfacher gerichteter Graph
G = nx.DiGraph()

# Zeitpunkte
timesteps = [1, 2, 3]

# Knoten hinzufügen
G.add_node("a(0)")
for t in timesteps:
    G.add_nodes_from([f"x({t})", f"a({t})", f"z({t})", f"L({t})"])

# Kanten (Abhängigkeiten)
for t in timesteps:
    G.add_edge(f"a({t-1})", f"a({t})")
    G.add_edge(f"x({t})", f"a({t})")
    G.add_edge(f"a({t})", f"z({t})")
    G.add_edge(f"z({t})", f"L({t})")

# Feste Positionen (damit es schnell und übersichtlich bleibt)
pos = {
    "a(0)": (-1, 2),
    "x(1)": (0, 3), "a(1)": (0, 2), "z(1)": (0, 1), "L(1)": (0, 0),
    "x(2)": (2, 3), "a(2)": (2, 2), "z(2)": (2, 1), "L(2)": (2, 0),
    "x(3)": (4, 3), "a(3)": (4, 2), "z(3)": (4, 1), "L(3)": (4, 0)
}

# Zeichnen (mit geringem Overhead)
plt.figure(figsize=(8, 4))
nx.draw(
    G,
    pos,
    with_labels=True,
    node_size=800,
    node_color="#90CAF9",
    arrowsize=15,
    font_size=8
)
plt.title("Simplified Computational Graph of the RNN (t = 1..3)")
plt.axis("off")
plt.show(block=False)